# Specify the version of the Docker Compose file format
# version: '3.8'
# Define the services that will run in your application
services:

  # Configuration for the MySQL database service
  db:
    # Use the MySQL 8 Docker image
    image: mysql:8
    container_name: mysql
    environment:
      # Set the root password for MySQL
      MYSQL_ROOT_PASSWORD: password
      # Specify the name of the database to be created
      MYSQL_DATABASE: product
      # Specify the MySQL user and its password
      MYSQL_USER: product
      MYSQL_PASSWORD: password
    volumes:
      - db:/data/mysql
    networks:
      - db
    restart: unless-stopped

  # Configuration for the server application
  server:
    # Build the server image using the Dockerfile in the ./server directory
    container_name: server
    build:
      context: ./backend
    environment:
      # Set the Spring DataSource URL to connect to the MySQL database service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/product
      # Set the username for connecting to the MySQL database
      SPRING_DATASOURCE_USERNAME: product
      # Set the password for connecting to the MySQL database
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
      
  # Configuration for the client application
  # client:
  #   # Build the client image using the Dockerfile in the ./client directory
  #   build:
  #     context: ./frontend
  #   # Expose port 3000 on the host and map it to port 5173 in the container
  #   ports:
  #     - "3000:3000"
  #   # Depend on the server service, ensuring it starts before the client
  #   depends_on:
  #     - server
  #   restart: on-failure

networks:
  db:
    driver: bridge
volumes:
  db: